import Menu from "./components/menuNav/Menu";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portugal Inmobiliaria",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className="cuerpo-main">
        <Menu />
        {children}
      </body>
    </html>
  );
}
